-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE FlowThread (
  flowthread_id TEXT NOT NULL,
  flowthread_pageid INT NOT NULL,
  flowthread_userid INT NOT NULL,
  flowthread_username VARCHAR(255) NOT NULL,
  flowthread_text TEXT NOT NULL,
  flowthread_parentid TEXT DEFAULT NULL,
  flowthread_status SMALLINT NOT NULL,
  flowthread_like INT NOT NULL,
  flowthread_report INT NOT NULL,
  PRIMARY KEY(flowthread_id)
);

CREATE INDEX FlowThreadSearchByPage ON FlowThread (flowthread_pageid);


CREATE TABLE FlowThreadAttitude (
  flowthread_att_id TEXT NOT NULL, flowthread_att_type SMALLINT NOT NULL,
  flowthread_att_userid INT NOT NULL
);

CREATE UNIQUE INDEX FlowThreadSearchAttitude ON FlowThreadAttitude (
  flowthread_att_id, flowthread_att_userid
);


CREATE TABLE FlowThreadControl (
  flowthread_ctrl_pageid INT NOT NULL,
  flowthread_ctrl_status INT NOT NULL,
  PRIMARY KEY(flowthread_ctrl_pageid)
);
