-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/FlowThread (
  flowthread_id BLOB NOT NULL,
  flowthread_pageid INTEGER UNSIGNED NOT NULL,
  flowthread_userid INTEGER UNSIGNED NOT NULL,
  flowthread_username VARCHAR(255) NOT NULL,
  flowthread_text CLOB NOT NULL,
  flowthread_parentid BLOB DEFAULT NULL,
  flowthread_status SMALLINT UNSIGNED NOT NULL,
  flowthread_like INTEGER NOT NULL,
  flowthread_report INTEGER NOT NULL,
  PRIMARY KEY(flowthread_id)
);

CREATE INDEX FlowThreadSearchByPage ON /*_*/FlowThread (flowthread_pageid);


CREATE TABLE /*_*/FlowThreadAttitude (
  flowthread_att_id BLOB NOT NULL, flowthread_att_type SMALLINT UNSIGNED NOT NULL,
  flowthread_att_userid INTEGER UNSIGNED NOT NULL
);

CREATE UNIQUE INDEX FlowThreadSearchAttitude ON /*_*/FlowThreadAttitude (
  flowthread_att_id, flowthread_att_userid
);


CREATE TABLE /*_*/FlowThreadControl (
  flowthread_ctrl_pageid INTEGER UNSIGNED NOT NULL,
  flowthread_ctrl_status INTEGER NOT NULL,
  PRIMARY KEY(flowthread_ctrl_pageid)
);
