-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/FlowThread (
  flowthread_id VARBINARY(11) NOT NULL,
  flowthread_pageid INT UNSIGNED NOT NULL,
  flowthread_userid INT UNSIGNED NOT NULL,
  flowthread_username VARCHAR(255) NOT NULL,
  flowthread_text LONGTEXT NOT NULL,
  flowthread_parentid VARBINARY(11) DEFAULT NULL,
  flowthread_status TINYINT UNSIGNED NOT NULL,
  flowthread_like INT NOT NULL,
  flowthread_report INT NOT NULL,
  INDEX FlowThreadSearchByPage (flowthread_pageid),
  PRIMARY KEY(flowthread_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/FlowThreadAttitude (
  flowthread_att_id VARBINARY(11) NOT NULL,
  flowthread_att_type TINYINT UNSIGNED NOT NULL,
  flowthread_att_userid INT UNSIGNED NOT NULL,
  UNIQUE INDEX FlowThreadSearchAttitude (
    flowthread_att_id, flowthread_att_userid
  )
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/FlowThreadControl (
  flowthread_ctrl_pageid INT UNSIGNED NOT NULL,
  flowthread_ctrl_status INT NOT NULL,
  PRIMARY KEY(flowthread_ctrl_pageid)
) /*$wgDBTableOptions*/;
